name: Destroy Terraform Infrastructure from AWS

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

env:
  OIDC_ROLE: ${{ secrets.GITHUBACTIONSROLE }}
  AWS_ACCOUNT_ID: ${{ secrets.ACCOUNT }}
  ENV_VAR: dev

jobs:
  terraform:
    name: Terraform-Destroy
    runs-on: ubuntu-latest
    environment: AWS
    if: github.event.pull_request.merged == true && contains(join(github.event.pull_request.labels.*.name, ','), 'destroy')

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.OIDC_ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -backend-config="key=simple-log-service-infra/${ENV_VAR}/terraform.tfstate"

      - name: Select Dev Workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
